server:
  port: 8020
  servlet:
    context-path: /api
    session:
      timeout: 30000s
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:nisum;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2console
  flyway:
    enabled: true
    locations: classpath:/db/migration
security:
  basic:
    enabled: true
    authorize-mode: NONE