server:
  port: 8020
  servlet:
    context-path: /api
    session:
      timeout: 30000s
spring:
  application:
    name: nisum-brian-gomez-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:nisum;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
  cache:
    jcache:
      config: classpath:ehcache.xml
security:
  basic:
    enabled: true
    authorize-mode: NONE
nisum:
  jwt:
    secret: 2bj8@2!UGJ8y=