spring:
  datasource:
    url: jdbc:h2:mem:nisum;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2console
  flyway:
    enabled: true
    locations: classpath:/db/migration