CREATE TABLE IF NOT EXISTS USERS(
    id VARCHAR(100),
    name VARCHAR(40) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    modified DATETIME ON UPDATE CURRENT_TIMESTAMP(),
    last_login DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    is_active BOOLEAN NOT NULL DEFAULT true,
    token VARCHAR(200),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PHONES(
    id VARCHAR(100),
    number VARCHAR(14) NOT NULL,
    city_code VARCHAR(5) NOT NULL,
    country_code VARCHAR(5) NOT NULL,
    user_id UUID NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS REGULAR_EXP_PARAM(
    id VARCHAR(100),
    name VARCHAR(40) UNIQUE NOT NULL,
    regular_expression VARCHAR(200) NOT NULL,
    last_update DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
    PRIMARY KEY (id)
);